#!/bin/sh -e

VERSION=$(head -n 1 /mnt/root/etc/ngs-release)
if [ "$VERSION" != "3.50.0" ]; then
  echo "This script only supports Montage firmware version 3.50.0."
  echo "Warning: the binary file format changes between releases so byte"
  echo "offsets will need to be verified and updated for new versions."
  exit 1
fi >&2

cd /mnt/root/usr/share/yamaha/contents
if dd if=performance/3F0005-Performance.pfm bs=1 skip=4 count=20 2>/dev/null \
       | fgrep -q -e "CFX PopStudioGrand  " -e "CFX Studio          " \
     && dd if=performance.cfg bs=1 skip=366 count=20 2>/dev/null \
       | fgrep -q -e "CFX PopStudioGrand  " -e "CFX Studio          " \
     && dd if=performance.cfg bs=1 skip=387 count=20 2>/dev/null \
       | fgrep -q -e "CFX PopStudioGrand  " -e "CFX Studio          "; then
  echo "Replacing CFX PopStudioGrand preset with CFX Studio"
  cp /usr/share/fixed/3F0005-Performance.pfm performance/3F0005-Performance.pfm
  dd bs=1 count=20 if=performance/3F0005-Performance.pfm skip=4 \
    of=performance.cfg seek=366 conv=notrunc 2>/dev/null
  dd bs=1 count=20 if=performance/3F0005-Performance.pfm skip=4 \
    of=performance.cfg seek=387 conv=notrunc 2>/dev/null
else
  echo "CFX Stage performance not found: is this supported firmware?" >&2
  exit 1
fi
